apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
        podSubnet: 10.244.0.0/16
apiServer:
        ExtraArgs:
                service-node-port-range: "8000-31274"

---

kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
